# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./pgdata:/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: local
      PGDATA: /pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
