-- Up Migration

insert into groceries( name, organisation_id)
values ('Eggs', 1),
       ('Water', 1),
       ('Milk', 1),
       ('Kefir', 1),
       ('Broccoli', 1),
       ('Pak choi', 1),
       ('Salmon', 1),
       ('Onion', 1),
       ('Garlic', 1),
       ('Tomatoes', 1),
       ('Cherry tomatoes', 1),
       ('Vinegar', 1),
       ('Soy', 1),
       ('Chilli oil', 1),
       ('Hay', 1),
       ('Mixed nuts', 1),
       ('Bananas', 1),
       ('Grapes', 1),
       ('Curly kale', 1),
       ('Potatoes', 1),
       ('Salad', 1),
       ('Spring onion', 1),
       ('Tea', 1),
       ('Chicken liver', 1),
       ('Chicken', 1),
       ('Lamb', 1),
       ('Pork', 1),
       ('Sushi', 1),
       ('Avocado', 1);

