name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: upcloud
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - name: deploy
      run: | 
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} uptime
        sshpass -p "${{ secrets.PASSWORD }}" scp -v -P ${{ secrets.PORT }} -r dist ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/chores/api
